# Generated by Django 5.1.4 on 2024-12-09 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_options_alter_userprofile_managers_and_more'),
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('meeting_slots', models.JSONField(default=list)),
                ('member_details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_group', to='proposals.proposal')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader_groups', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='member_groups', to=settings.AUTH_USER_MODEL)),
                ('preferences', models.ManyToManyField(blank=True, related_name='preferred_groups', to='proposals.proposal')),
            ],
        ),
    ]
