# Generated by Django 5.1.4 on 2024-12-10 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.member'),
        ),
        migrations.AlterField(
            model_name='group',
            name='meeting_slots',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='member_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
