# Generated by Django 5.1.4 on 2024-12-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_group_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='leader',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
